In [6]:
import pandas as pd
from sklearn.metrics import f1_score, accuracy_score

In [7]:
gold_df = pd.read_csv(r'/home/aatman/Aatman/Study/Challenges in Computatinal Linguistics/code/data/subtask1/dev/hin.csv', lineterminator='\n')
gold_df.shape

(137, 3)

In [8]:
gold_df.head()

,id,text,polarization\r
0,hin_4e26c967ea5fd015078d088118fb623c,और इस तरह बीजेपी ने अपना इस्लामीकरण कर लिया,1
1,hin_ad83fddd1620ad95784072561ea3d3d0,ओरीजनल हिंदुत्व यही है ।,1
2,hin_21522a5233b239644c874f8b52890d70,हिंदुत्व की चर्बी उतर गई,1
3,hin_b7fa87154f21b0abd1eac2c3973c7812,हिंदू एवम हिंदुत्व जाग रहा है। जय श्री राम,0
4,hin_d3e4ed943e52657cc4ad3c76d6747d60,बोल अपने आका को हिन्दू और हिंदुत्व है .......घ...,1

In [9]:
grok_df = pd.read_csv(r'hin_grok_output.csv')
grok_df.shape

(137, 3)

In [10]:
grok_df.head()

                                                text polarized Unnamed: 2
0        और इस तरह बीजेपी ने अपना इस्लामीकरण कर लिया       Yes        NaN
1                           ओरीजनल हिंदुत्व यही है ।       Yes        NaN
2                           हिंदुत्व की चर्बी उतर गई       Yes        NaN
3         हिंदू एवम हिंदुत्व जाग रहा है। जय श्री राम       Yes        NaN
4  बोल अपने आका को हिन्दू और हिंदुत्व है .......घ...       Yes        NaN

In [11]:
# check if text is same in both
(gold_df['text'] == grok_df['text']).all()

np.True_

In [12]:
merged = gold_df.merge(
    grok_df,
    on='text',
    how='inner'
)
merged.shape

(137, 5)

In [13]:
merged['grok_label'] = merged['polarized'].map({
    'Yes': 1,
    'No': 0
})

In [15]:
merged

,id,text,polarization\r,polarized,Unnamed: 2,grok_label
0,hin_4e26c967ea5fd015078d088118fb623c,और इस तरह बीजेपी ने अपना इस्लामीकरण कर लिया,1,Yes,NaN,1
1,hin_ad83fddd1620ad95784072561ea3d3d0,ओरीजनल हिंदुत्व यही है ।,1,Yes,NaN,1
2,hin_21522a5233b239644c874f8b52890d70,हिंदुत्व की चर्बी उतर गई,1,Yes,NaN,1
3,hin_b7fa87154f21b0abd1eac2c3973c7812,हिंदू एवम हिंदुत्व जाग रहा है। जय श्री राम,0,Yes,NaN,1
4,hin_d3e4ed943e52657cc4ad3c76d6747d60,बोल अपने आका को हिन्दू और हिंदुत्व है .......घ...,1,Yes,NaN,1
...,...,...,...,...,...,...
132,hin_276a07823dff0cf8f98ee5a376691cd7,दम है तो ऐसे किसी खालिस्तानी को लेकर आओ,1,Yes,NaN,1
133,hin_d2e9d70dfd34b9307d39cfef38e965de,अगर ये ही हाल रहा तो देखना पंजाब फिर से खालिस्...,1,Yes,NaN,1
134,hin_19aee977bce61fa8b1cf67a126e441b3,"खालिस्तानी, इस्लामिक आतंकवादी चरण की शुरुआत तो...",1,Yes,NaN,1
135,hin_584f49ebcca4ff3ead3ff4f2d9caf331,रही बात 700 किसानों की तो राकेश टिकैत साहब जवा...,1,Yes,NaN,1
136,hin_3e28313b41e9b3ebba63bef3c033aaea,आंदोलनजीवी दुबारा निकले बिल से 😡😡😡🧐🧐🧐🧐🧐🧐,1,Yes,NaN,1

In [16]:
merged[['polarization\r', 'polarized', 'grok_label']].head()

   polarization\r polarized  grok_label
0               1       Yes           1
1               1       Yes           1
2               1       Yes           1
3               0       Yes           1
4               1       Yes           1

In [18]:
y_true = merged['polarization\r']
y_pred = merged['grok_label']

f1_macro = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

f1_macro, accuracy

(0.630976430976431, 0.7664233576642335)